<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../App.Application/App.Application.csproj" />
    <ProjectReference Include="../App.Infrastructure/App.Infrastructure.csproj" />
  </ItemGroup>
</Project>
